name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      # 1. تحميل المشروع
      - name: Checkout project
        uses: actions/checkout@v4

      # 2. Python الخاص بـ GitHub Actions
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      # 3. Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      # 4. تثبيت متطلبات Linux
      - name: Install system dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            libltdl-dev \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            ccache \
            lld

      # 5. تثبيت Buildozer و Cython
      - name: Install Buildozer
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "Cython==0.29.36"
          python -m pip install "buildozer==1.5.0"

      # 6. التأكد من الإصدارات
      - name: Check build environment
        run: |
          echo "========== Python =========="
          python --version

          echo "========== Java =========="
          java -version

          echo "========== Buildozer =========="
          buildozer --version

          echo "========== Cython =========="
          cython --version

      # 7. تنظيف أي ملفات بناء قديمة
      - name: Clean Buildozer
        run: |
          rm -rf .buildozer
          rm -rf bin

      # 8. بناء APK
      - name: Build APK
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PYTHONUNBUFFERED: "1"
        run: |
          echo "========================================"
          echo "Starting Android build"
          echo "Python:"
          python --version
          echo "========================================"

          yes | buildozer -v android debug

      # 9. التأكد من وجود APK
      - name: Check APK
        run: |
          echo "========== APK FILES =========="
          ls -lah bin/

      # 10. رفع APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Calculator-APK
          path: bin/*.apk
          if-no-files-found: error
